const LATEX_SYMBOLS: Record<string, string> = {
  '\\rightarrow': '→',
  '\\leftarrow': '←',
  '\\Rightarrow': '⇒',
  '\\Leftarrow': '⇐',
  '\\mapsto': '↦',
  '\\longmapsto': '⟼',
  '\\to': '→',
  '\\gets': '←',
  '\\implies': '⟹',
  '\\impliedby': '⟸',
  '\\iff': '⟺',
  '\\leftrightarrow': '↔',
  '\\Leftrightarrow': '⇔',
  '\\uparrow': '↑',
  '\\downarrow': '↓',
  '\\Uparrow': '⇑',
  '\\Downarrow': '⇓',
  '\\updownarrow': '↕',
  '\\nearrow': '↗',
  '\\searrow': '↘',
  '\\swarrow': '↙',
  '\\nwarrow': '↖',
  '\\alpha': 'α',
  '\\beta': 'β',
  '\\gamma': 'γ',
  '\\delta': 'δ',
  '\\epsilon': 'ε',
  '\\zeta': 'ζ',
  '\\eta': 'η',
  '\\theta': 'θ',
  '\\iota': 'ι',
  '\\kappa': 'κ',
  '\\lambda': 'λ',
  '\\mu': 'μ',
  '\\nu': 'ν',
  '\\xi': 'ξ',
  '\\omicron': 'ο',
  '\\pi': 'π',
  '\\rho': 'ρ',
  '\\sigma': 'σ',
  '\\tau': 'τ',
  '\\upsilon': 'υ',
  '\\phi': 'φ',
  '\\chi': 'χ',
  '\\psi': 'ψ',
  '\\omega': 'ω',
  '\\Gamma': 'Γ',
  '\\Delta': 'Δ',
  '\\Theta': 'Θ',
  '\\Lambda': 'Λ',
  '\\Xi': 'Ξ',
  '\\Pi': 'Π',
  '\\Sigma': 'Σ',
  '\\Phi': 'Φ',
  '\\Psi': 'Ψ',
  '\\Omega': 'Ω',
  '\\infty': '∞',
  '\\sum': '∑',
  '\\prod': '∏',
  '\\int': '∫',
  '\\oint': '∮',
  '\\partial': '∂',
  '\\nabla': '∇',
  '\\approx': '≈',
  '\\sim': '∼',
  '\\simeq': '≃',
  '\\cong': '≅',
  '\\equiv': '≡',
  '\\neq': '≠',
  '\\ne': '≠',
  '\\leq': '≤',
  '\\geq': '≥',
  '\\ll': '≪',
  '\\gg': '≫',
  '\\subset': '⊂',
  '\\supset': '⊃',
  '\\subseteq': '⊆',
  '\\supseteq': '⊇',
  '\\cup': '∪',
  '\\cap': '∩',
  '\\in': '∈',
  '\\notin': '∉',
  '\\emptyset': '∅',
  '\\exists': '∃',
  '\\forall': '∀',
  '\\neg': '¬',
  '\\vee': '∨',
  '\\wedge': '∧',
  '\\oplus': '⊕',
  '\\otimes': '⊗',
  '\\bot': '⊥',
  '\\top': '⊤',
  '\\vdash': '⊢',
  '\\dashv': '⊣',
  '\\models': '⊧',
  '\\cdots': '⋯',
  '\\vdots': '⋮',
  '\\ddots': '⋱',
  '\\ldots': '…',
  '\\cdot': '·',
  '\\times': '×',
  '\\div': '÷',
  '\\pm': '±',
  '\\mp': '∓',
  '\\ast': '∗',
  '\\star': '⋆',
  '\\circ': '∘',
  '\\bullet': '•',
  '\\surd': '√',
  '\\sqrt': '√',
  '\\angle': '∠',
  '\\triangle': '△',
  '\\ell': 'ℓ',
  '\\aleph': 'ℵ',
  '\\hbar': 'ℏ',
  '\\Re': 'ℜ',
  '\\Im': 'ℑ',
  '\\mathbb': '',
};

export function convertLatex(text: string): string {
  const sortedKeys = Object.keys(LATEX_SYMBOLS).sort(
    (a, b) => b.length - a.length,
  );
  const pattern = new RegExp(
    sortedKeys
      .map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
      .join('|'),
    'g',
  );

  const mathBlocks: string[] = [];
  const PLACEHOLDER = '%%KATEX_BLOCK_';

  const withoutMath = text.replace(
    /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\))/g,
    (match) => {
      mathBlocks.push(match);
      return `${PLACEHOLDER}${mathBlocks.length - 1}%%`;
    },
  );

  const converted = withoutMath.replace(
    pattern,
    (match) => LATEX_SYMBOLS[match] || match,
  );

  return converted.replace(
    /%%KATEX_BLOCK_(\d+)%%/g,
    (_, idx) => mathBlocks[parseInt(idx)] || '',
  );
}
